version: "3.4"

services:
  subuntu:
    container_name: "subuntu"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/var/data
      - C:\Program Files (x86)\Tesseract-OCR\tessdata:/etc/tesseract-ocr/tessdata
      - C:\Users\amrul\programming\datasets\uzbek_nlp_dataset\izohli_lugat\drive-download-20230121T035915Z-001\uzbek_tilining_izohli_lugati_t_www.ziyouz.com:/var/datasets/izohli_lugat
    environment:
      - TESSDATA_PREFIX:/etc/tesseract-ocr/tessdata
    ports:
      - 3000:80
    command: ["systemctl","start","mysimplewsgi"]